### ISSUE TITLE
You will not be redirected to Admin Panel after Setup

### ISSUE THREAD

**Issue by AlexL777** [trendschau/typemill#11]
Hi Developers,

I wanted to get in touch and give feedback on the new Typemill version. Unfortunately, I was not forwarded to the admin panel and could not create the new user. The directory `/settings` but I deleted before.

Why is that me?

Thanks in Advance.

**Comment by trendschau** [comment]
Hi Alex, 

did you update the whole "system" folder? Because the urls for the admin panel changed from "tm-author" to "tm", maybe that is the problem. If that is not the problem, can you explain more detailed? Tests on localhost are successful and I could also update a live website without problems. Do you have a special workflow for updates?

Will try to look into that on the weekend...

Thank you
Sebastian

**Comment by AlexL777** [comment]
Hi,

I forgot again that you have to update every time you update Composer. You may be able to include this in your tutorial, because it is very important to know that beforehand.

Otherwise, creating a new user worked well. One more question: Does this have to look like the one on the screenshot below, because it's in the middle of the design. The content I mean.

Thank you.

![typemill-version-1-1-x](https://user-images.githubusercontent.com/7885632/40502930-b2edc956-5f8c-11e8-9db6-52dcb9831023.jpg)

**Comment by trendschau** [comment]
Ok, glad to hear that, I already updated the "update" tutorial with a section about GitHub and Composer: https://typemill.net/getting-started/update

I know it is a bit uncomfortable right now, but some libraries (e.g. parsedown) constantly make problems if they are included in the GitHub repository, so I decided to exclude the vendor folder completely. 

The startpage should look like on the typemill.net website, but at the end, it is up to the theme-developers how they adapt the design :) I did not make cross-browser-tests so far...

Cheers
Sebastian
